name: flutter_blue_background
description: A new Flutter plugin project.
version: 0.0.1
homepage:
publish_to: none #https://github.com/DoanpPhiHo/flutter_blue_background

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2
  blue_handle_data:
    git:
      url: https://github.com/DoanpPhiHo/flutter_blue_background
      path: packages/blue_handle_data
  # blue_async:
  #   git: 
  #     url: https://github.com/DoanpPhiHo/blue_async
  #     ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.hodoan.flutter_blue_background
        pluginClass: FlutterBlueBackgroundPlugin
      ios:
        pluginClass: FlutterBlueBackgroundPlugin