name: blue_handle_data
description: A new Flutter plugin project.
version: 0.0.1
homepage:

# isar_version: &isar_version 3.0.4

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  convert: ^3.1.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  # isar: *isar_version
  # isar_flutter_libs: *isar_version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # isar_generator: *isar_version
  # build_runner: any
flutter: